version: '3.8'

services:
  sky-take-out-service:  # Spring Boot 应用服务
    build:
      context: .  # Dockerfile 所在目录
      dockerfile: Dockerfile  # 指定 Dockerfile 路径
    container_name: sky-take-out-service
    networks:
      - sky-take-out-network
    depends_on:
      - mysql-service
      - redis-service
      - minio-service

  mysql-service:  # MySQL 服务
    image: mysql:9.3.0
    container_name: mysql-service
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "./sky-server/src/main/resources/initdb:/docker-entrypoint-initdb.d"
    networks:
      - sky-take-out-network

  redis-service:  # Redis 服务
    image: redis:8.0.3
    container_name: redis-service
    command: redis-server --requirepass 123456 --appendonly yes
    networks:
      - sky-take-out-network

  minio-service:  # MinIO 服务
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    container_name: minio-service
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    networks:
      - sky-take-out-network

  nginx-service:  # Nginx 服务
    image: nginx:1.29.0
    container_name: nginx-service
    ports:
      - "80:80"
    volumes:
      - "./sky-server/src/main/resources/front/html:/usr/share/nginx/html"
      - "./sky-server/src/main/resources/front/conf/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - sky-take-out-service
    networks:
      - sky-take-out-network

networks:
  sky-take-out-network:  # 自定义内部网络
    driver: bridge
