sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: sky-take-out

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wxb4ca15d63fa04e17
    secret: 3563d4f0d54a7966d587cc1b6108ea57
